add_executable(defaultTranslator defaultTranslator.C)
add_dependencies(defaultTranslator ROSE_DLL)
target_link_libraries(defaultTranslator ROSE_DLL)
install(TARGETS defaultTranslator DESTINATION bin)

add_executable(KeepGoingTranslator KeepGoingTranslator.cpp)
add_dependencies(KeepGoingTranslator ROSE_DLL)
target_link_libraries(KeepGoingTranslator ROSE_DLL)
install(TARGETS KeepGoingTranslator DESTINATION bin)

add_executable(preprocessingInfoDumper preprocessingInfoDumper.C)
add_dependencies(preprocessingInfoDumper ROSE_DLL)
target_link_libraries(preprocessingInfoDumper ROSE_DLL)
install(TARGETS preprocessingInfoDumper DESTINATION bin)

add_executable(mangledNameDumper mangledNameDumper.C)
add_dependencies(mangledNameDumper ROSE_DLL)
target_link_libraries(mangledNameDumper ROSE_DLL)
install(TARGETS mangledNameDumper DESTINATION bin)

add_executable(qualifiedNameDumper qualifiedNameDumper.C)
add_dependencies(qualifiedNameDumper ROSE_DLL)
target_link_libraries(qualifiedNameDumper ROSE_DLL)
install(TARGETS qualifiedNameDumper DESTINATION bin)

add_executable(textASTGenerator textASTGenerator.C)
add_dependencies(textASTGenerator ROSE_DLL)
target_link_libraries(textASTGenerator ROSE_DLL)
install(TARGETS textASTGenerator DESTINATION bin)

if(TARGET rose_clang_libstdcxx_headers)
  target_link_libraries(defaultTranslator PRIVATE rose_clang_libstdcxx_headers)
  target_link_libraries(KeepGoingTranslator PRIVATE rose_clang_libstdcxx_headers)
  target_link_libraries(preprocessingInfoDumper PRIVATE rose_clang_libstdcxx_headers)
  target_link_libraries(mangledNameDumper PRIVATE rose_clang_libstdcxx_headers)
  target_link_libraries(qualifiedNameDumper PRIVATE rose_clang_libstdcxx_headers)
  target_link_libraries(textASTGenerator PRIVATE rose_clang_libstdcxx_headers)
endif()
