
// These cpp declarations control the use of different versions of STL
// each STL version has different ways (names) of including files etc.
// These are set by the configuration mechanism for ROSE.

// DQ (5/27/2007): I don't think we need this! And if not we don't need this
// whole file except maybe as a place to put header file that does not force
// fixing up Rosetta to generate the separate header file includes directly.

// BP : 10/25/2001, needed for getcwd
// #include <unistd.h>

// DQ (5/27/2007): Commented out since this header file has been removed
// This is a base class used in the classes generated by ROSETTA
// #include "grammarBaseClass.h"
