      PROGRAM FIXED_FORMAT_STRING_BOUNDARY
      CHARACTER*16 CFMT, IFMT, LFMT, RFMT
      PARAMETER
     1(CFMT='(8A16)', IFMT='(10I12)', LFMT='(L8)', RFMT='(1P,5E24.16)')
      WRITE (*,RFMT) 1.0
      END
