/* Shared unparser formatting event types. */

#ifndef UNPARSE_FORMAT_TYPES_H
#define UNPARSE_FORMAT_TYPES_H

typedef enum Format_Opt {
  FORMAT_BEFORE_DIRECTIVE,
  FORMAT_AFTER_DIRECTIVE,
  FORMAT_BEFORE_STMT,
  FORMAT_AFTER_STMT,
  FORMAT_BEFORE_BASIC_BLOCK1,
  FORMAT_AFTER_BASIC_BLOCK1,
  FORMAT_BEFORE_BASIC_BLOCK2,
  FORMAT_AFTER_BASIC_BLOCK2,
  FORMAT_BEFORE_NESTED_STATEMENT,
  FORMAT_AFTER_NESTED_STATEMENT
} FormatOpt;

#endif
