/**
 * Generates random class hierarchies
 *
 * - first a random graph of arbitrary size is generated
 * - then loops are removed ( no loops allowed in a c++ class hierarchy)
 * - when the following situation occurs there is a compiler warning (ambiguity
 * of a): c0 -> c1 c2 c1 -> c2 i.e. for an edge (0->2) there exist a longer path
 * (0->1->2) so for every edge there is checked if such a path exist, if yes,
 * this edge is removed
 * - the resulting graph is printed out in topological order, therefore a map
 * exist, which maps classNr to fileNr ( because multiple classes can be printed
 * in one file)
 */

#include <algorithm>
#include <cassert>
#include <cctype>
#include <cstdlib>
#include <ctime>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <queue>
#include <random>
#include <set>
#include <sstream>
#include <string>
#include <unordered_set>
#include <utility>
#include <vector>

using namespace std;

namespace fs = std::filesystem;

using Edge = std::pair<int, int>;

struct Graph {
  explicit Graph(size_t vertexCount) : outEdges(vertexCount) {}

  size_t size() const { return outEdges.size(); }

  void add_edge(int src, int dst) { outEdges.at(src).push_back(dst); }

  void remove_edge(int src, int dst) {
    vector<int> &edges = outEdges.at(src);
    edges.erase(remove(edges.begin(), edges.end(), dst), edges.end());
  }

  const vector<int> &out(int v) const { return outEdges.at(v); }

  vector<int> &out(int v) { return outEdges.at(v); }

private:
  vector<vector<int>> outEdges;
};

/// Maps a class/vertex to a file
map<int, int> vertexToFileId;

/// name of the folder where the output files are printed
string outputFolderName;

void printMap() {
  cout << "vertexToFileId Map" << endl;
  for (map<int, int>::iterator i = vertexToFileId.begin();
       i != vertexToFileId.end(); ++i)
    cout << i->first << " " << i->second << endl;
}

/// used for #ifndef argument - convertes everything to uppercase and replaces
/// '.' by '_'
string StringToUpper(const string &strToConvert) {
  string res = strToConvert;
  for (unsigned int i = 0; i < strToConvert.length(); i++) {
    res[i] = static_cast<char>(toupper(strToConvert[i]));

    if (strToConvert[i] == '.')
      res[i] = '_';
  }

  return res;
}

/// generates a vector of count distinct class-names
void generateClassNames(int count, vector<string> &nameVec) {
  for (int i = 0; i < count; i++) {
    stringstream s;
    s << "c_" << i;
    nameVec.push_back(s.str());
  }
}

/// opens outputfiles in the outputFolder and returns vector of ostreams
/// prints the #ifndef FILENAME_H on the top
void generateOutStreams(const vector<string> &fileNames,
                        vector<ostream *> &ostreamVec) {
  ostreamVec.clear();
  ostreamVec.reserve(fileNames.size());

  for (size_t i = 0; i < fileNames.size(); i++) {
    stringstream path;
    path << outputFolderName << "/" << fileNames[i];
    std::ofstream *stream = new std::ofstream(path.str().c_str());
    ostreamVec.push_back(stream);

    *stream << "#ifndef " << StringToUpper(fileNames[i]) << endl;
    *stream << "#define " << StringToUpper(fileNames[i]) << endl << endl;
  }
}

/// function to close the open streams generated by generateOutStreams() , and
/// closes #ifndef FILENAME_H
void closeOutStream(vector<ostream *> ostreamVec) {
  for (size_t i = 0; i < ostreamVec.size(); i++) {
    *(ostreamVec[i]) << endl << "#endif" << endl;
    ostreamVec[i]->flush();
    delete ostreamVec[i];
  }
}

/// prints a file with an empty main function, which includes all generated
/// headers
void printMain(const vector<string> &headerFiles) {
  stringstream fileName;
  fileName << outputFolderName << "/"
           << "main.cpp";
  std::ofstream os(fileName.str().c_str());

  for (size_t i = 0; i < headerFiles.size(); i++)
    os << "#include \"" << headerFiles[i] << "\"" << endl;

  os << endl;
  os << "int main(int argc, char**argv)" << endl;
  os << "{ " << endl << "\treturn 0; " << endl << "}" << endl << endl;
}

/// generates list of outputfile names
void generateFileNames(int count, vector<string> &nameVec) {
  for (int i = 0; i < count; i++) {
    stringstream s;
    s << "file_" << i << ".h";
    nameVec.push_back(s.str());
  }
}

/// checks on which files a class(i.e. vertex) depends, and adds the file to the
/// set
void getDependendFiles(set<int> &files, int v, const Graph &g) {
  for (int depNode : g.out(v)) {
    assert(vertexToFileId.find(depNode) != vertexToFileId.end());

    int fileId = vertexToFileId[depNode];

    files.insert(fileId);
  }
}

/// print a graph to a stream in adjacency list notation
void printGraph(ostream &os, Graph &g, const vector<string> &vertexNames) {
  for (size_t i = 0; i < g.size(); ++i) {
    if (g.out(static_cast<int>(i)).empty())
      continue;

    os << vertexNames[i] << " -> ";

    for (int targetVertex : g.out(static_cast<int>(i)))
      os << vertexNames[targetVertex] << " ";

    os << endl;
  }
}

void printGraphToFile(Graph &g, const vector<string> &vertexNames) {
  stringstream fileName;
  fileName << outputFolderName << "/"
           << "dumpfile.cmp.out";
  std::ofstream os(fileName.str().c_str());
  printGraph(os, g, vertexNames);
}

void generateRandomGraph(Graph &g, size_t edgeCount, std::mt19937 &rng) {
  const size_t vertexCount = g.size();
  if (vertexCount == 0)
    return;

  const size_t maxEdges = vertexCount * (vertexCount - 1);
  edgeCount = std::min(edgeCount, maxEdges);

  std::uniform_int_distribution<int> dist(0, static_cast<int>(vertexCount - 1));
  std::unordered_set<uint64_t> seen;
  seen.reserve(edgeCount * 2 + 1);

  while (seen.size() < edgeCount) {
    int src = dist(rng);
    int dst = dist(rng);
    if (src == dst)
      continue;
    uint64_t key =
        static_cast<uint64_t>(src) * vertexCount + static_cast<uint64_t>(dst);
    if (!seen.insert(key).second)
      continue;
    g.add_edge(src, dst);
  }
}

void dfsRemoveLoops(int v, Graph &g, vector<int> &color,
                    vector<Edge> &backEdges) {
  color[v] = 1;
  for (int targetVertex : g.out(v)) {
    if (color[targetVertex] == 0) {
      dfsRemoveLoops(targetVertex, g, color, backEdges);
    } else if (color[targetVertex] == 1) {
      backEdges.emplace_back(v, targetVertex);
    }
  }
  color[v] = 2;
}

void removeLoops(Graph &g) {
  vector<int> color(g.size(), 0);
  vector<Edge> backEdges;
  for (size_t i = 0; i < g.size(); ++i) {
    if (color[i] == 0)
      dfsRemoveLoops(static_cast<int>(i), g, color, backEdges);
  }

  for (const Edge &edge : backEdges)
    g.remove_edge(edge.first, edge.second);
}

/// checks if v2 is reachable from v1, when all edges in the deletedEdges-set
/// are not available
int isReachable2(Graph &g, int v1, int v2, const set<Edge> &deletedEdges) {
  int counter = 0;

  vector<bool> visited(g.size(), false);

  queue<int> bfsQueue;

  bfsQueue.push(v1);
  visited[v1] = true;

  while (!bfsQueue.empty()) {
    const int curVertex = bfsQueue.front();
    bfsQueue.pop();

    for (int targetVertex : g.out(curVertex)) {
      if (deletedEdges.find(std::make_pair(curVertex, targetVertex)) !=
          deletedEdges.end())
        continue;

      if (!visited[targetVertex])
        bfsQueue.push(targetVertex);

      visited[targetVertex] = true;

      if (targetVertex == v2)
        counter++;
    }
  }

  return counter;
}

void writeClassToFile(ostream &os, const vector<string> &classNames, int v,
                      const Graph &g) {
  os << "class " << classNames[v] << " ";

  if (!g.out(v).empty())
    os << " : ";

  bool firstBase = true;
  for (int targetVertex : g.out(v)) {
    if (!firstBase)
      os << ", ";
    firstBase = false;
    os << "public " << classNames[targetVertex];
  }

  os << endl;
  os << "{};" << endl << endl;
}

void removeAmbiguityWarning2(Graph &g) {
  set<Edge> deletedEdges;
  vector<Edge> edgesToRemove;

  for (size_t src = 0; src < g.size(); ++src) {
    for (int dst : g.out(static_cast<int>(src))) {
      int counter = isReachable2(g, static_cast<int>(src), dst, deletedEdges);
      if (counter > 1) {
        deletedEdges.insert(std::make_pair(static_cast<int>(src), dst));
        edgesToRemove.emplace_back(static_cast<int>(src), dst);
      }
    }
  }

  for (const Edge &edge : edgesToRemove)
    g.remove_edge(edge.first, edge.second);
}

vector<int> topologicalSort(const Graph &g) {
  vector<int> inDegree(g.size(), 0);
  for (size_t src = 0; src < g.size(); ++src) {
    for (int dst : g.out(static_cast<int>(src)))
      ++inDegree[dst];
  }

  queue<int> zeroQueue;
  for (size_t i = 0; i < inDegree.size(); ++i) {
    if (inDegree[i] == 0)
      zeroQueue.push(static_cast<int>(i));
  }

  vector<int> order;
  order.reserve(g.size());
  while (!zeroQueue.empty()) {
    int v = zeroQueue.front();
    zeroQueue.pop();
    order.push_back(v);
    for (int dst : g.out(v)) {
      if (--inDegree[dst] == 0)
        zeroQueue.push(dst);
    }
  }

  assert(order.size() == g.size());
  return order;
}

int fileIdFromClassId(int classId, int numClasses, int numFiles) {
  int classesPerFile = numClasses / numFiles;

  return classId / classesPerFile;
}

int main(int argc, char **argv) {
  size_t classCount = 50;
  size_t fileCount = 50;

  // arg0 progname
  // arg1 classCount
  // arg2 fileCount
  // arg3 egdeRate
  // arg4 folderName

  if (argc != 5) {
    cerr << "Class Hierarchy Testfile Generator:" << endl;
    cerr << "Usage:" << endl;
    cerr << "./classHierarchyTestGen <classCount> <fileCount> <edgeRate> "
            "<outputFolderName>"
         << endl;
    return 1;
  }

  classCount = atoi(argv[1]);
  fileCount = atoi(argv[2]);
  float edgeRate = atof(argv[3]);

  // DQ (9/12/2011): Enforce checking on inputs (issue detected by static
  // analysis).
  assert(classCount >= 0 && classCount < 10000);
  assert(fileCount >= 0 && fileCount < 10000);
  assert(edgeRate >= 0.0 && edgeRate < 10000.0);

  outputFolderName = string(argv[4]);

  if (classCount < fileCount) {
    cerr << "More files than classes!";
    return 1;
  }

  fs::create_directories(outputFolderName);

  vector<string> classNames;
  generateClassNames(static_cast<int>(classCount), classNames);

  Graph g(classCount);

  // Generate random graph
  std::mt19937 rng(static_cast<unsigned int>(time(NULL)));
  rng.seed(32);
  generateRandomGraph(g, static_cast<size_t>(edgeRate * classCount), rng);

  // remove cycles
  removeLoops(g);
  removeAmbiguityWarning2(g);

  // topological sort
  vector<int> vlist = topologicalSort(g);

  assert(fileCount <= classCount);

  vector<ostream *> ostreamVec;
  vector<string> fileNameVec;
  generateFileNames(static_cast<int>(fileCount), fileNameVec);
  generateOutStreams(fileNameVec, ostreamVec);

  int classesPerFile = static_cast<int>(classCount / fileCount);
  if (classCount % fileCount != 0)
    classesPerFile++;

  // write a map, which vertex/class comes into which file
  int vCount = 0;
  for (int vertex : vlist) {
    int fileId = vCount / classesPerFile;
    vertexToFileId.emplace(vertex, fileId);
    vCount++;
  }

  vector<int>::iterator vIter = vlist.begin();
  for (size_t file = 0; file < fileCount; file++) {
    stringstream includePart;
    stringstream contentPart;

    set<int> depFiles;
    for (int c = 0; c < classesPerFile; c++) {
      getDependendFiles(depFiles, *vIter, g);

      writeClassToFile(contentPart, classNames, *vIter, g);

      vIter++;
      if (vIter == vlist.end())
        break;
    }

    // remove dependency to current file (otherwise the own include would be
    // included)
    depFiles.erase(static_cast<int>(file));
    for (set<int>::iterator i = depFiles.begin(); i != depFiles.end(); ++i)
      includePart << "#include \"" << fileNameVec[*i] << "\"" << endl;

    *(ostreamVec[file]) << includePart.str() << endl
                        << contentPart.str() << endl;
  }

  printGraphToFile(g, classNames);

  closeOutStream(ostreamVec);

  printMain(fileNameVec);

  return 0;
}
