add_library(roseAstNodesExpression OBJECT
  SgActualArgumentExpression.C
  SgAddressOfOp.C
  SgAggregateInitializer.C
  SgAlignOfOp.C
  SgAndOp.C
  SgArrowExp.C
  SgArrowStarOp.C
  SgAsmOp.C
  SgAssignInitializer.C
  SgAssumedRankExp.C
  SgAsteriskShapeExp.C
  SgAwaitExpression.C
  SgBinaryOp.C
  SgBitComplementOp.C
  SgBracedInitializer.C
  SgCAFCoExpression.C
  SgCAFImageSelectorExp.C
  SgCallExpression.C
  SgCastExp.C
  SgChar16Val.C
  SgChar32Val.C
  SgClassExp.C
  SgColonShapeExp.C
  SgCommaOpExp.C
  SgComplexVal.C
  SgConditionalExp.C
  SgConstructorInitializer.C
  SgCudaKernelCallExp.C
  SgDeleteExp.C
  SgDesignatedInitializer.C
  SgDesignator.C
  SgDotExp.C
  SgDotStarOp.C
  SgEnumVal.C
  SgExponentiationOp.C
  SgExpression.C
  SgExprListExp.C
  SgFoldExpression.C
  SgFunctionCallExp.C
  SgFunctionParameterRefExp.C
  SgFunctionRefExp.C
  SgFortranCommonBlockRefExp.C
  SgImpliedDo.C
  SgLabelRefExp.C
  SgLambdaExp.C
  SgMacroExpansionExp.C
  SgMemberFunctionRefExp.C
  SgMinusMinusOp.C
  SgNewExp.C
  SgNoexceptOp.C
  SgNonrealRefExp.C
  SgOrOp.C
  SgOmpApplyTransformation.C
  SgOmpInductionItem.C
  SgOmpInitModifier.C
  SgOmpInitModifierList.C
  SgOmpAppendArgsOperation.C
  SgOmpMapDistDataPolicy.C
  SgOmpMapItem.C
  SgOmpNameExpression.C
  SgOmpDirectiveLocalRefExp.C
  SgOmpSourceExpression.C
  SgPackExpansionExpr.C
  SgPlusPlusOp.C
  SgPntrArrRefExp.C
  SgPointerDerefExp.C
  SgPseudoDestructorRefExp.C
  SgRangeExp.C
  SgSizeOfOp.C
  SgStatementExpression.C
  SgStringVal.C
  SgSubscriptExpression.C
  SgSuperExp.C
  SgTemplateFunctionRefExp.C
  SgTemplateMemberFunctionRefExp.C
  SgTemplateParameterVal.C
  SgThisExp.C
  SgThrowOp.C
  SgTypeExpression.C
  SgTypeRequirement.C
  SgTypeIdOp.C
  SgTypeTraitBuiltinOperator.C
  SgUnaryOp.C
  SgUnknownArrayOrFunctionReference.C
  SgUserDefinedBinaryOp.C
  SgUserDefinedUnaryOp.C
  SgVarArgEndOp.C
  SgVarArgOp.C
  SgVarRefExp.C
  SgWcharVal.C
)

add_dependencies(roseAstNodesExpression rosetta_generated)
