#include "sage3basic.h"

void SgAggregateInitializer::post_construction_initialization() {
  if (get_source_form() == e_aggregate_initializer_source_unclassified) {
    fprintf(stderr,
            "REX_AST_INVARIANT[aggregate-initializer-source-form]: source "
            "form is unclassified\n");
    ROSE_ABORT();
  }
  if (get_initializers()) {
    get_initializers()->set_parent(this);
  }
}

// DQ: trying to remove the nested iterator class
void SgAggregateInitializer::append_initializer(SgExpression *what) {
  if (p_initializers == nullptr || what == nullptr ||
      what->get_parent() != nullptr) {
    fprintf(stderr,
            "REX_AST_INVARIANT[aggregate-initializer-append]: exact list and "
            "detached nonnull element are required\n");
    ROSE_ABORT();
  }
  p_initializers->append_expression(what);
  what->set_parent(p_initializers);
}

SgExpression *SgAggregateInitializer::get_next(int &n) const {
  if (n == 0) {
    n++;
    return get_initializers();
  } else
    return 0;
}

int SgAggregateInitializer::replace_expression(SgExpression *o,
                                               SgExpression *n) {
  // DQ (12/17/2006): This function should have the semantics that it will
  // represent a structural change to the AST, thus it is free to set the parent
  // of the new expression.

  ROSE_ASSERT(o != NULL);
  ROSE_ASSERT(n != NULL);

  if (get_initializers() == o) {
    set_initializers(isSgExprListExp(n));
    n->set_parent(this);
    return 1;
  } else {
    return 0;
  }
}

SgType *SgAggregateInitializer::get_type() const {
  if (p_expression_type == nullptr ||
      isSgTypeUnknown(p_expression_type) != nullptr ||
      isSgTypeDefault(p_expression_type) != nullptr) {
    fprintf(stderr,
            "REX_AST_INVARIANT[aggregate-initializer-type]: initializer has "
            "no exact semantic type\n");
    ROSE_ABORT();
  }
  return p_expression_type;
}

// DQ (6/11/2015): Moved these eight access functions, they should not be
// generated by ROSETTA so that we could avoid them setting the isModified flag
// which is a problem in the name qualification support for C++ (interfering
// with the token-based unparsing).
bool SgAggregateInitializer::get_requiresGlobalNameQualificationOnType() const {
  ROSE_ASSERT(this != NULL);
  return p_requiresGlobalNameQualificationOnType;
}

void SgAggregateInitializer::set_requiresGlobalNameQualificationOnType(
    bool requiresGlobalNameQualificationOnType) {
  ROSE_ASSERT(this != NULL);
  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

  p_requiresGlobalNameQualificationOnType =
      requiresGlobalNameQualificationOnType;
}

int SgAggregateInitializer::get_name_qualification_length_for_type() const {
  ROSE_ASSERT(this != NULL);
  return p_name_qualification_length_for_type;
}

void SgAggregateInitializer::set_name_qualification_length_for_type(
    int name_qualification_length_for_type) {
  ROSE_ASSERT(this != NULL);
  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

  p_name_qualification_length_for_type = name_qualification_length_for_type;
}

bool SgAggregateInitializer::get_type_elaboration_required_for_type() const {
  ROSE_ASSERT(this != NULL);
  return p_type_elaboration_required_for_type;
}

void SgAggregateInitializer::set_type_elaboration_required_for_type(
    bool type_elaboration_required_for_type) {
  ROSE_ASSERT(this != NULL);
  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

  p_type_elaboration_required_for_type = type_elaboration_required_for_type;
}

bool SgAggregateInitializer::get_global_qualification_required_for_type()
    const {
  ROSE_ASSERT(this != NULL);
  return p_global_qualification_required_for_type;
}

void SgAggregateInitializer::set_global_qualification_required_for_type(
    bool global_qualification_required_for_type) {
  ROSE_ASSERT(this != NULL);
  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

  p_global_qualification_required_for_type =
      global_qualification_required_for_type;
}
