#include "sage3basic.h"

void SgTemplateMemberFunctionRefExp::post_construction_initialization() {}

SgTemplateMemberFunctionSymbol *
SgTemplateMemberFunctionRefExp::get_symbol() const {
  // return isSgTemplateMemberFunctionSymbol(get_symbol_i());
  return get_symbol_i();
}

void SgTemplateMemberFunctionRefExp::set_symbol(
    SgTemplateMemberFunctionSymbol *symbol) {
  set_symbol_i(symbol);
}

// DQ (2/8/2009): I always wanted to have this function!
SgMemberFunctionDeclaration *
SgTemplateMemberFunctionRefExp::getAssociatedMemberFunctionDeclaration() const {
  SgTemplateMemberFunctionSymbol *memberFunctionSymbol = get_symbol();
  SgMemberFunctionDeclaration *sourceTemplate =
      memberFunctionSymbol != nullptr
          ? isSgMemberFunctionDeclaration(
                memberFunctionSymbol->get_declaration())
          : nullptr;
  SgMemberFunctionDeclaration *semanticFunction =
      get_semantic_member_function_declaration();
  if (memberFunctionSymbol == nullptr || sourceTemplate == nullptr ||
      isSgTemplateMemberFunctionDeclaration(sourceTemplate) == nullptr ||
      semanticFunction == nullptr || semanticFunction->get_type() == nullptr) {
    fprintf(stderr,
            "REX_AST_INVARIANT[template-member-function-reference]: "
            "reference=%p symbol=%p source-template=%p semantic-function=%p "
            "has no exact source and semantic callable identities\n",
            static_cast<const void *>(this),
            static_cast<void *>(memberFunctionSymbol),
            static_cast<void *>(sourceTemplate),
            static_cast<void *>(semanticFunction));
    ROSE_ABORT();
  }
  return semanticFunction;
}

// DQ (6/11/2015): Moved these six access functions, they should not be
// generated by ROSETTA so that we could avoid them setting the isModified flag
// which is a problem in the name qualification support for C++ (interfering
// with the token-based unparsing).
int SgTemplateMemberFunctionRefExp::get_name_qualification_length() const {
  ROSE_ASSERT(this != NULL);
  return p_name_qualification_length;
}

void SgTemplateMemberFunctionRefExp::set_name_qualification_length(
    int name_qualification_length) {
  ROSE_ASSERT(this != NULL);
  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

  p_name_qualification_length = name_qualification_length;
}

bool SgTemplateMemberFunctionRefExp::get_type_elaboration_required() const {
  ROSE_ASSERT(this != NULL);
  return p_type_elaboration_required;
}

void SgTemplateMemberFunctionRefExp::set_type_elaboration_required(
    bool type_elaboration_required) {
  ROSE_ASSERT(this != NULL);
  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

  p_type_elaboration_required = type_elaboration_required;
}

bool SgTemplateMemberFunctionRefExp::get_global_qualification_required() const {
  ROSE_ASSERT(this != NULL);
  return p_global_qualification_required;
}

void SgTemplateMemberFunctionRefExp::set_global_qualification_required(
    bool global_qualification_required) {
  ROSE_ASSERT(this != NULL);

  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

  p_global_qualification_required = global_qualification_required;
}

int SgTemplateMemberFunctionRefExp::get_explicit_name_qualification_length()
    const {
  ROSE_ASSERT(this != NULL);
  return p_explicit_name_qualification_length;
}

void SgTemplateMemberFunctionRefExp::set_explicit_name_qualification_length(
    int explicit_name_qualification_length) {
  ROSE_ASSERT(this != NULL);
  p_explicit_name_qualification_length = explicit_name_qualification_length;
}

bool SgTemplateMemberFunctionRefExp::get_explicit_global_qualification() const {
  ROSE_ASSERT(this != NULL);
  return p_explicit_global_qualification;
}

void SgTemplateMemberFunctionRefExp::set_explicit_global_qualification(
    bool explicit_global_qualification) {
  ROSE_ASSERT(this != NULL);
  p_explicit_global_qualification = explicit_global_qualification;
}

const SgStringList &
SgTemplateMemberFunctionRefExp::get_explicit_name_qualification_tokens() const {
  ROSE_ASSERT(this != NULL);
  return p_explicit_name_qualification_tokens;
}

SgStringList &
SgTemplateMemberFunctionRefExp::get_explicit_name_qualification_tokens() {
  ROSE_ASSERT(this != NULL);
  return p_explicit_name_qualification_tokens;
}

void SgTemplateMemberFunctionRefExp::set_explicit_name_qualification_tokens(
    const SgStringList &explicit_name_qualification_tokens) {
  ROSE_ASSERT(this != NULL);
  p_explicit_name_qualification_tokens = explicit_name_qualification_tokens;
}
