#include "sage3basic.h"

void SgTemplateFunctionRefExp::post_construction_initialization() {}

SgTemplateFunctionSymbol *SgTemplateFunctionRefExp::get_symbol() const {
  // return isSgTemplateFunctionSymbol(get_symbol_i());
  return get_symbol_i();
}

void SgTemplateFunctionRefExp::set_symbol(SgTemplateFunctionSymbol *symbol) {
  set_symbol_i(symbol);
}

SgFunctionDeclaration *
SgTemplateFunctionRefExp::getAssociatedFunctionDeclaration() const {
  SgTemplateFunctionSymbol *functionSymbol = this->get_symbol();
  SgFunctionDeclaration *sourceTemplate =
      functionSymbol != nullptr ? functionSymbol->get_declaration() : nullptr;
  SgFunctionDeclaration *semanticFunction = get_semantic_function_declaration();
  if (functionSymbol == nullptr || sourceTemplate == nullptr ||
      isSgTemplateFunctionDeclaration(sourceTemplate) == nullptr ||
      semanticFunction == nullptr || semanticFunction->get_type() == nullptr) {
    fprintf(stderr,
            "REX_AST_INVARIANT[template-function-reference]: reference=%p "
            "symbol=%p source-template=%p semantic-function=%p has no exact "
            "source and semantic callable identities\n",
            static_cast<const void *>(this),
            static_cast<void *>(functionSymbol),
            static_cast<void *>(sourceTemplate),
            static_cast<void *>(semanticFunction));
    ROSE_ABORT();
  }
  return semanticFunction;
}

// DQ (6/11/2015): Moved these six access functions, they should not be
// generated by ROSETTA so that we could avoid them setting the isModified flag
// which is a problem in the name qualification support for C++ (interfering
// with the token-based unparsing).
int SgTemplateFunctionRefExp::get_name_qualification_length() const {
  ROSE_ASSERT(this != NULL);
  return p_name_qualification_length;
}

void SgTemplateFunctionRefExp::set_name_qualification_length(
    int name_qualification_length) {
  ROSE_ASSERT(this != NULL);
  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

  p_name_qualification_length = name_qualification_length;
}

bool SgTemplateFunctionRefExp::get_type_elaboration_required() const {
  ROSE_ASSERT(this != NULL);
  return p_type_elaboration_required;
}

void SgTemplateFunctionRefExp::set_type_elaboration_required(
    bool type_elaboration_required) {
  ROSE_ASSERT(this != NULL);
  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

  p_type_elaboration_required = type_elaboration_required;
}

bool SgTemplateFunctionRefExp::get_global_qualification_required() const {
  ROSE_ASSERT(this != NULL);
  return p_global_qualification_required;
}

void SgTemplateFunctionRefExp::set_global_qualification_required(
    bool global_qualification_required) {
  ROSE_ASSERT(this != NULL);

  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

  p_global_qualification_required = global_qualification_required;
}

int SgTemplateFunctionRefExp::get_explicit_name_qualification_length() const {
  ROSE_ASSERT(this != NULL);
  return p_explicit_name_qualification_length;
}

void SgTemplateFunctionRefExp::set_explicit_name_qualification_length(
    int explicit_name_qualification_length) {
  ROSE_ASSERT(this != NULL);
  p_explicit_name_qualification_length = explicit_name_qualification_length;
}

bool SgTemplateFunctionRefExp::get_explicit_global_qualification() const {
  ROSE_ASSERT(this != NULL);
  return p_explicit_global_qualification;
}

void SgTemplateFunctionRefExp::set_explicit_global_qualification(
    bool explicit_global_qualification) {
  ROSE_ASSERT(this != NULL);
  p_explicit_global_qualification = explicit_global_qualification;
}

const SgStringList &
SgTemplateFunctionRefExp::get_explicit_name_qualification_tokens() const {
  ROSE_ASSERT(this != NULL);
  return p_explicit_name_qualification_tokens;
}

SgStringList &
SgTemplateFunctionRefExp::get_explicit_name_qualification_tokens() {
  ROSE_ASSERT(this != NULL);
  return p_explicit_name_qualification_tokens;
}

void SgTemplateFunctionRefExp::set_explicit_name_qualification_tokens(
    const SgStringList &explicit_name_qualification_tokens) {
  ROSE_ASSERT(this != NULL);
  p_explicit_name_qualification_tokens = explicit_name_qualification_tokens;
}
