#include "sage3basic.h"

SgType *SgTypeIdOp::get_type() const {
  SgType *resultType = get_expression_type();
  SgReferenceType *referenceType = isSgReferenceType(resultType);
  if (referenceType == nullptr || referenceType->get_base_type() == nullptr ||
      !SageInterface::isConstType(referenceType->get_base_type()) ||
      isSgTypeUnknown(resultType) != nullptr ||
      isSgTypeDefault(resultType) != nullptr) {
    std::cerr << "REX_AST_INVARIANT[typeid-result-type]: typeid expression "
                 "must store its exact const reference result type\n";
    ROSE_ABORT();
  }
  return resultType;
}

// DQ (6/11/2015): Moved these six access functions, they should not be
// generated by ROSETTA so that we could avoid them setting the isModified flag
// which is a problem in the name qualification support for C++ (interfering
// with the token-based unparsing).
int SgTypeIdOp::get_name_qualification_length() const {
  ROSE_ASSERT(this != NULL);
  return p_name_qualification_length;
}

void SgTypeIdOp::set_name_qualification_length(int name_qualification_length) {
  ROSE_ASSERT(this != NULL);
  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

  p_name_qualification_length = name_qualification_length;
}

bool SgTypeIdOp::get_type_elaboration_required() const {
  ROSE_ASSERT(this != NULL);
  return p_type_elaboration_required;
}

void SgTypeIdOp::set_type_elaboration_required(bool type_elaboration_required) {
  ROSE_ASSERT(this != NULL);
  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

  p_type_elaboration_required = type_elaboration_required;
}

bool SgTypeIdOp::get_global_qualification_required() const {
  ROSE_ASSERT(this != NULL);
  return p_global_qualification_required;
}

void SgTypeIdOp::set_global_qualification_required(
    bool global_qualification_required) {
  ROSE_ASSERT(this != NULL);

  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

  p_global_qualification_required = global_qualification_required;
}

// DQ (4/15/2019): These six access functions should not be generated by ROSETTA
// so that we could avoid them setting the isModified flag which is a problem in
// the name qualification support for C++ (interfering with the token-based
// unparsing).
int SgTypeIdOp::get_name_qualification_for_pointer_to_member_class_length()
    const {
  ROSE_ASSERT(this != NULL);
  return p_name_qualification_for_pointer_to_member_class_length;
}

void SgTypeIdOp::set_name_qualification_for_pointer_to_member_class_length(
    int name_qualification_length) {
  ROSE_ASSERT(this != NULL);
  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

  p_name_qualification_for_pointer_to_member_class_length =
      name_qualification_length;
}

bool SgTypeIdOp::get_type_elaboration_for_pointer_to_member_class_required()
    const {
  ROSE_ASSERT(this != NULL);
  return p_type_elaboration_for_pointer_to_member_class_required;
}

void SgTypeIdOp::set_type_elaboration_for_pointer_to_member_class_required(
    bool type_elaboration_required) {
  ROSE_ASSERT(this != NULL);
  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

  p_type_elaboration_for_pointer_to_member_class_required =
      type_elaboration_required;
}

bool SgTypeIdOp::get_global_qualification_for_pointer_to_member_class_required()
    const {
  ROSE_ASSERT(this != NULL);
  return p_global_qualification_for_pointer_to_member_class_required;
}

void SgTypeIdOp::set_global_qualification_for_pointer_to_member_class_required(
    bool global_qualification_required) {
  ROSE_ASSERT(this != NULL);

  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

  p_global_qualification_for_pointer_to_member_class_required =
      global_qualification_required;
}
