##########################################################################################
# This makefile is unfinished and does not yet generate Rosetta documentation.
##########################################################################################

# Makefile rule called by automake (using dist or install rules)
docs:
	@echo "Skipping the creation of documentation within the docs rule (for now)."

EXTRA_DIST = CMakeLists.txt
