# OpenMP Fortran test source list.
set(OPENMP_FORTRAN_TESTCODES
  allocate_predefined_modifiers.f90
  allocate_user_defined_modifiers.f90
  default.f
  exampleA251f.f
  flush.f
  helloworld.f
  helloworld0.f
  helloworld2.f
  master.f
  ompdo-decremental.f
  ompdo-default.f
  ompdo-orphaned.f
  ompdo-static.f
  parallel-1.f
  parallel-2.f
  parallel.f
  private.f
  reduction.f
  schedule.f
  section1.f
  shared.f
  single.f
  task_largenumber.f
  task_largenumber2.f
  task_scalar.f
  task_simplest.f
  testNewOFP.f
  paralleldo.f90
  paralleldo-1.f90
  critical.f90
  continuation.f90
  single-copyprivate.f90
  parallel-if.f
  parallel-if-numthreads.f
  barrier.f
  exampleA11f.f
  exampleA211f.f
  exampleA281f.f
  exampleA102f.f90
  exampleA161f.f90
  flush2.f
  exmpaleA221f.f
  conditional.f
  exampleA41f.f90
  exampleA134f.f90
  ompdo-decremental-2.f
  array-one.f
  array_initialize.f
  jacobi.f
  ompdo-multiple.f
  shared-array.f
  collapse.f90
)
