if(NOT DEFINED REX_CTEST_BUILD_DIR OR REX_CTEST_BUILD_DIR STREQUAL "")
  message(FATAL_ERROR "REX_CTEST_BUILD_DIR is required.")
endif()
if(NOT DEFINED REX_CTEST_GROUP_TESTS OR REX_CTEST_GROUP_TESTS STREQUAL "")
  message(STATUS "REX_CTEST_GROUP_TESTS is empty; nothing to run.")
  return()
endif()
list(LENGTH REX_CTEST_GROUP_TESTS _group_len)
if(_group_len EQUAL 1)
  list(GET REX_CTEST_GROUP_TESTS 0 _group_single)
  if(_group_single MATCHES "\\\\;")
    string(REPLACE "\\;" ";" _group_single "${_group_single}")
    set(REX_CTEST_GROUP_TESTS "${_group_single}")
  endif()
endif()

set(_parallel "16")
if(DEFINED ENV{CTEST_PARALLEL_LEVEL} AND NOT "$ENV{CTEST_PARALLEL_LEVEL}" STREQUAL "")
  set(_parallel "$ENV{CTEST_PARALLEL_LEVEL}")
endif()
if(DEFINED REX_CTEST_PARALLEL AND NOT REX_CTEST_PARALLEL STREQUAL "")
  set(_parallel "${REX_CTEST_PARALLEL}")
endif()

set(_config "")
if(DEFINED ENV{CTEST_CONFIGURATION_TYPE} AND NOT "$ENV{CTEST_CONFIGURATION_TYPE}" STREQUAL "")
  set(_config "$ENV{CTEST_CONFIGURATION_TYPE}")
endif()
if(DEFINED REX_CTEST_CONFIG AND NOT REX_CTEST_CONFIG STREQUAL "")
  set(_config "${REX_CTEST_CONFIG}")
endif()

set(_regex "")
foreach(_test IN LISTS REX_CTEST_GROUP_TESTS)
  if(_test STREQUAL "")
    continue()
  endif()
  set(_escaped "${_test}")
  string(REGEX REPLACE "([][.^$*+?()|{}\\\\])" "\\\\\\1" _escaped "${_escaped}")
  if(_regex STREQUAL "")
    set(_regex "${_escaped}")
  else()
    set(_regex "${_regex}|${_escaped}")
  endif()
endforeach()

if(_regex STREQUAL "")
  message(STATUS "REX_CTEST_GROUP_TESTS resolved to an empty regex; nothing to run.")
  return()
endif()
set(_regex "^(${_regex})$")

set(_ctest_cmd "ctest")
if(DEFINED REX_CTEST_COMMAND AND NOT REX_CTEST_COMMAND STREQUAL "")
  set(_ctest_cmd "${REX_CTEST_COMMAND}")
endif()

set(_cmd "${_ctest_cmd}" "--test-dir" "${REX_CTEST_BUILD_DIR}" "-R" "${_regex}" "--output-on-failure")
if(_parallel)
  list(APPEND _cmd "-j" "${_parallel}")
endif()
if(_config)
  list(APPEND _cmd "-C" "${_config}")
endif()

execute_process(COMMAND ${_cmd} RESULT_VARIABLE _result)
if(NOT _result EQUAL 0)
  message(FATAL_ERROR "CTest group failed with exit code ${_result}.")
endif()
