#include "Rose/StringUtility.h"

#include "rose.h"

#include <chrono>

#include <filesystem>

#include <fstream>

#include <map>

using namespace std;
using namespace Rose::StringUtility;

namespace {
namespace fs = std::filesystem;

void touchFile(const fs::path &path) {
  fs::create_directories(path.parent_path());
  ofstream file(path);
  ROSE_ASSERT(file.good());
  file << "// generated by testFileNameClassifier\n";
}

void expectClassification(const FileNameClassification &classification,
                          FileNameLocation location,
                          const FileNameLibrary &library) {
  ROSE_ASSERT(classification.getLocation() == location);
  ROSE_ASSERT(classification.getLibrary() == library);
}
} // namespace

int main(int argc, char **argv) {
  const string uniqueSuffix =
      to_string(std::chrono::steady_clock::now().time_since_epoch().count());
  const fs::path sandbox = fs::temp_directory_path() /
                           ("rex-testFileNameClassifier-" + uniqueSuffix);

  const fs::path appRoot = sandbox / "app";
  const fs::path userHeader = appRoot / "src" / "user.h";
  const fs::path cHeader = sandbox / "vendor-c" / "include" / "stdio.h";
  const fs::path roseHeader = sandbox / "vendor-rose" / "include" / "rose.h";
  const fs::path stlHeader = sandbox / "vendor-stl" / "include" / "vector";
  const fs::path mappedHeader =
      sandbox / "vendor-custom" / "include" / "custom.h";
  const fs::path missingHeader = sandbox / "missing" / "does_not_exist.h";

  touchFile(userHeader);
  touchFile(cHeader);
  touchFile(roseHeader);
  touchFile(stlHeader);
  touchFile(mappedHeader);

  const string sourceDir = appRoot.string();

  FileNameClassification classification =
      classifyFileName(missingHeader.string(), sourceDir);
  expectClassification(classification, FILENAME_LOCATION_NOT_EXIST,
                       FILENAME_LIBRARY_UNKNOWN);
  ROSE_ASSERT(classification.getDistanceFromSourceDirectory() == 0);

  classification = classifyFileName(userHeader.string(), sourceDir);
  expectClassification(classification, FILENAME_LOCATION_USER,
                       FILENAME_LIBRARY_USER);
  ROSE_ASSERT(classification.getDistanceFromSourceDirectory() == 0);

  classification = classifyFileName(cHeader.string(), sourceDir);
  expectClassification(classification, FILENAME_LOCATION_LIBRARY,
                       FILENAME_LIBRARY_C);

  classification = classifyFileName(roseHeader.string(), sourceDir);
  expectClassification(classification, FILENAME_LOCATION_LIBRARY,
                       FILENAME_LIBRARY_ROSE);

  classification = classifyFileName(stlHeader.string(), sourceDir);
  expectClassification(classification, FILENAME_LOCATION_LIBRARY,
                       FILENAME_LIBRARY_STL);

  map<string, string> customLibraries;
  customLibraries[(sandbox / "vendor-custom").string()] = "ThirdParty";
  classification =
      classifyFileName(mappedHeader.string(), sourceDir, customLibraries);
  expectClassification(classification, FILENAME_LOCATION_LIBRARY, "ThirdParty");

  // Test header filename cleanup routine

  ROSE_ASSERT(stripDotsFromHeaderFileName(". FileNameClassifier.h") ==
              "FileNameClassifier.h");
  ROSE_ASSERT(
      stripDotsFromHeaderFileName(".................. "
                                  "/usr/lib/gcc/i386-redhat-linux/3.4.6/../../"
                                  "../../include/c++/3.4.6/string") ==
      "/usr/lib/gcc/i386-redhat-linux/3.4.6/../../../../include/c++/3.4.6/"
      "string");
  ROSE_ASSERT(stripDotsFromHeaderFileName("") == "");
  ROSE_ASSERT(stripDotsFromHeaderFileName("test.h") == "test.h");
  ROSE_ASSERT(stripDotsFromHeaderFileName(" test.h") == "test.h");
  ROSE_ASSERT(stripDotsFromHeaderFileName("test... .h") == "test... .h");

  std::error_code ec;
  fs::remove_all(sandbox, ec);
  ROSE_ASSERT(!ec);

  return 0;
}
