
########### next target ###############


########### install files ###############

install(FILES  nodeQuery.h nodeQueryInheritedAttribute.h       booleanQuery.h booleanQueryInheritedAttribute.h       nameQuery.h nameQueryInheritedAttribute.h       numberQuery.h numberQueryInheritedAttribute.h       astQuery.h astQueryInheritedAttribute.h       collectAssociateNodes.h       roseQueryLib.h DESTINATION ${INCLUDE_INSTALL_DIR})
