/* SPDX-License-Identifier: ISC */
#ifndef TEST2018_34_SUPPORT_CONFIG_H
#define TEST2018_34_SUPPORT_CONFIG_H

#define STDC_HEADERS 1
#define HAVE_STDLIB_H 1
#define HAVE_STDBOOL_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_UNISTD_H 1
#define HAVE_ISBLANK 1
#define HAVE_DECL_ERRNO 1

#endif
