## A sample Makefile to build a ROSE tool.
##
## Important: remember that Makefile recipes must contain tabs:
##
##     <target>: [ <dependency > ]*
##         [ <TAB> <command> <endl> ]+
## So you have to replace spaces with Tabs if you copy&paste this file from a browser!

## ROSE installation contains
##   * libraries, e.g. "librose.la"
##   * headers, e.g. "rose.h"
ROSE_PREFIX ?= $(shell rose-config prefix)
ROSE_CONFIG ?= $(ROSE_PREFIX)/bin/rose-config

ROSE_CXX ?= $(shell $(ROSE_CONFIG) ROSE_CXX)
ROSE_CPPFLAGS := $(shell $(ROSE_CONFIG) ROSE_CPPFLAGS)
ROSE_CXXFLAGS := $(shell $(ROSE_CONFIG) ROSE_CXXFLAGS)
ROSE_LDFLAGS := $(shell $(ROSE_CONFIG) ROSE_LDFLAGS)
ROSE_LINK_RPATHS := $(shell $(ROSE_CONFIG) ROSE_LINK_RPATHS)

## Your translator
TRANSLATOR=rajaChecker
TRANSLATOR_SOURCE=$(TRANSLATOR).C

## Input testcode for your translator
TESTCODE=hello.cpp

LINK_FLAGS=$(ROSE_LDFLAGS) $(ROSE_LINK_RPATHS)
#-------------------------------------------------------------
# Makefile Targets
#-------------------------------------------------------------

all: $(TRANSLATOR)

# compile the translator and generate an executable
# -g is recommended to be used by default to enable debugging your code
$(TRANSLATOR): $(TRANSLATOR_SOURCE)
	$(ROSE_CXX) -g $(ROSE_CPPFLAGS) $(ROSE_CXXFLAGS) $(TRANSLATOR_SOURCE) $(LINK_FLAGS) -o $(TRANSLATOR)

# test the translator
check: $(TRANSLATOR)
	./$(TRANSLATOR) -c -I. -I$(ROSE_PREFIX)/include $(TESTCODE)

clean:
	rm -rf $(TRANSLATOR) *.o rose_* *.dot
